laravel-order-fulfilment-system/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Homepage/Dashboard
Route::get('/', 'OrderController@index')->name('home');

// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
//Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
//Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

// 'Orders' resource controller
Route::resource('orders', 'OrderController')->except([
  'index'
]); // Can add in other resource routes as an array if required ( use resources() )

Route::get('/orders', function () {
  return abort(404);
});

// Orders Attach Files Routes
Route::post('/orders/action', 'OrderController@action')->name('ajaxuploadfile.action');
Route::get('/orders/files/uploads/{storage_filename}/{original_filename}', 'OrderController@files');

// Order Cron Jobs
Route::get('/cron/delete_old_orders', 'OrderController@deleteOldOrders');

laravel-order-fulfilment-system/resources/views/inc/grand-total.blade.php
<div class="row">
    <div class="form-group col-6">
        <button type="submit" class="btn btn-primary d-print-none">{{ isset($order) ? "Update Order" : "Create Order" }}</button>
        @if (isset($order))
            <button type="button" class="btn btn-danger ml-3 d-print-none" data-toggle="modal" data-target="#deleteOrder">Delete Order</button>
        @endif
    </div>
    <div class="col-6 grand-total">
        <p><b>Grand Total:</b> £@{{total}}</p>
    </div>
</div>

laravel-order-fulfilment-system/resources/views/inc/item.blade.php
<transition-group name="slide-fade"class="row no-gutters" tag="div">
    <div class="item col-12 ml-0" v-for="(item, index) in items" v-bind:key="item">
        <div class="card">
            <div class="card-body">
                <transition name="fade">
                    <div v-if="items.length > 1" class="row delete-item-button-container">
                        <div class="col">
                            <button type="button" class="btn btn-danger btn-sm float-right mb-2 d-print-none" data-toggle="modal" :data-target="'#deleteItem-' + index">x</button>
                        </div>
                    </div>
                </transition>
                <div class="row">
                    <div class="col-6">
                        <div class="row">
                            <div class="form-group col-6">
                                <label class="mb-1 font-weight-bold">Size</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="size" placeholder="Enter size" :name="'items[' + index + '][size]'" v-model="item.size">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <label for="material" class="mb-1 font-weight-bold">Material</label>
                                <div class="input-group">
                                    <select class="custom-select" id="material" :name="'items[' + index + '][material]'" v-model="item.material">
                                        <option value="">Choose...</option>
                                        <option value="Brushed Stainless">Brushed Stainless</option>
                                        <option value="Polished Stainless">Polished Stainless</option>
                                        <option value="Brushed Brass">Brushed Brass</option>
                                        <option value="Polished Brass">Polished Brass</option>
                                        <option value="Bronze">Bronze</option>
                                        <option value="Aluminium">Aluminium</option>
                                        <option value="Free Issue">Free Issue</option>
                                        <option value="Other">Other</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group col-6">
                                <label class="mb-1 font-weight-bold">Thickness</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="thickness" placeholder="Enter thickness" :name="'items[' + index + '][thickness]'" v-model="item.thickness">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <label class="mb-1 font-weight-bold">Infill</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="infill" placeholder="Enter infill" :name="'items[' + index + '][infill]'" v-model="item.infill">
                                </div>
                            </div>
                            <div class="form-group col-6">
                                <label class="mb-1 font-weight-bold">Holes</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="holes" placeholder="Enter holes" :name="'items[' + index + '][holes]'" v-model="item.holes">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-4">
                                <label class="mb-1 font-weight-bold">Quantity</label>
                                <div class="input-group">
                                    <input type="number" min="0" step="1" class="form-control{{ $errors->has('quantity') ? ' is-invalid' : '' }}" id="quantity" placeholder="Enter quantity" v-on:change="updateSubtotal(index)" :name="'items[' + index + '][quantity]'" v-model="item.quantity">
                                    <div class="invalid-feedback">
                                        Please provide a valid quantity.
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-4">
                                <label class="mb-1 font-weight-bold">Price</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="currency">£</span>
                                    </div>
                                    <input type="number" min="0" max="999999" step="0.01" class="form-control{{ $errors->has('price') ? ' is-invalid' : '' }}" id="price" placeholder="Enter price" :name="'items[' + index + '][price]'" v-on:change="updateSubtotal(index)" v-model="item.price" aria-describedby="currency">
                                    <div class="invalid-feedback">
                                        Please provide a valid price.
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-4">
                                <label class="mb-1 font-weight-bold">Subtotal</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="currency">£</span>
                                    </div>
                                    <input type="number" readonly class="form-control" v-model="item.subtotal" aria-describedby="currency">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-6 pl-4">
                        <label class="mb-1 font-weight-bold">Engraving</label>
                        <div class="input-group">
                            <textarea class="form-control{{ $errors->has('engraving') ? ' is-invalid' : '' }}" rows="12" id="engraving" placeholder="Enter engraving details" :name="'items[' + index + '][engraving]'" v-model="item.engraving"></textarea>
                            <div class="invalid-feedback">
                                This is a required field.
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row d-print-none">
                    <div class="col">
                        <div class="form-check float-right">
                            <label class="form-check-label bg-light p-2 rounded font-weight-bold" :for="'completed-' + index">
                                <input type="checkbox" class="mr-2" :id="'completed-' + index" :name="'items[' + index + '][completed]'" v-model="item.completed">

                                Item Completed
                            </label>
                        </div>
                    </div>
                </div>
                <div class="modal fade" :id="'deleteItem-' + index" tabindex="-1" role="dialog" aria-labelledby="deleteItem" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="exampleModalLongTitle">Delete Item</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                Are you sure you want to delete this item?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-danger" data-dismiss="modal" v-on:click="deleteItem(index)">Delete</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</transition-group>

laravel-order-fulfilment-system/resources/views/inc/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
        <div class="container">
          <a class="navbar-brand" href="{{ url('/') }}">
            <img src="{{ asset('images/hockerill-engraving-logo.png') }}" alt="Logo"/>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
              <!-- Authentication Links -->
              @guest
                <li class="nav-item">
                  <a class="nav-link" href="{{ route('login') }}">
                    <i class="fas fa-sign-in-alt"></i> {{ __('Login') }}
                  </a>
                </li>
                <li class="nav-item">
                  @if (Route::has('register'))
                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                  @endif
                </li>
              @else
              {{--Dashboard Nav Items--}}
              @if (Request::is('/'))
              <li class="nav-item">
                <a href="{{ route('orders.create') }}" class="nav-link">
                    <i class="fas fa-plus-circle"></i> New Order
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link jquery-print">
                  <i class="fas fa-print"></i> Print
                </a>
              </li>
              <li class="nav-item">
                <div class="search-container">

                </div>
              </li>

            {{--Create Order Nav Items--}}
            @elseif (Request::is('orders/create'))
            <li class="nav-item">
              <a href="/" class="nav-link">
                <i class="fas fa-chevron-circle-left"></i> Back
              </a>
            </li>

            {{--Order Nav Items--}}
            @elseif (Request::is('orders/*'))
              <li class="nav-item">
                <a href="/" class="nav-link">
                  <i class="fas fa-chevron-circle-left"></i> Back
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link jquery-print">
                  <i class="fas fa-print"></i> Print
                </a>
              </li>
              <li class="nav-item">
                {{--Delete button uses modal code in view to perform it's duties--}}
                <a href="#" class="nav-link" data-toggle="modal" data-target="#deleteOrder">
                  <i class="fas fa-trash"></i> Delete
                </a>
              </li>

            @endif

                <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                    <i class="fas fa-user"></i> {{--{{ Auth::user()->name }}--}} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{ route('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    <i class="fas fa-sign-out-alt"></i> {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      @csrf
                    </form>
                  </div>
                </li>
              @endguest
            </ul>
          </div>
        </div>
      </nav>

laravel-order-fulfilment-system/resources/views/inc/print.blade.php
<div class="container print-header d-none d-print-block">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="row align-items-center">
                <div class="col-8">
                    <img class="print-logo" src="{{ asset('images/hockerill-engraving-logo.png') }}" alt="Logo"/>
                </div>
                <div class="col-4">
                    <p class="text-right">
                        Unit 7a Mendip Business Park<br/>
                        Rooksbridge<br/>
                        BS26 2UG<br/>
                        Tel: 01934 750042<br/>
                        info@hockerillengraving.co.uk<br/>
                        www.hockerillengraving.co.uk<br/>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

laravel-order-fulfilment-system/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Favicons -->
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url('apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url('favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url('favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url('site.webmanifest') }}">
  <link rel="mask-icon" href="{{ url('safari-pinned-tab.svg') }}" color="#ff6600">
  <link rel="shortcut icon" href="{{ url('favicon.ico') }}">
  <meta name="msapplication-TileColor" content="#ff6600">
  <meta name="msapplication-config" content="{{ url('browserconfig.xml') }}">
  <meta name="theme-color" content="#ff6600">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'Hockerill Engraving') }}</title>

  <!-- Scripts -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="{{ asset('js/app.js') }}" defer></script>
  <script defer type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
  <script defer type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>
  <script defer type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/b-print-1.5.4/r-2.2.2/datatables.min.js"></script>
  <script defer type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
  <script defer type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.js"></script>

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/b-print-1.5.4/r-2.2.2/datatables.min.css"/>

  <!-- Fonts -->
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

</head>
<body>
  <div id="app">
    @include('inc.navbar')
    <main class="py-4">
      @yield('content')
    </main>
  </div>
  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/5b4606f26d961556373d9e71/1cte5kesn';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);
  })();
  </script>
  <!--End of Tawk.to Script-->
</body>
</html>

laravel-order-fulfilment-system/resources/views/orders/create.blade.php
@extends('layouts.app')
@section('content')
@include('inc.print')
<div class="container" id="orders">
    <form action="{{ isset($order) ? route('orders.update', $order->id) : route('orders.store') }}" method="POST" class="needs-validation" novalidate>
        @csrf {{-- Include CSRF protection --}}
        @if (isset($order))
            @method('PUT')
        @endif

        <div class="row justify-content-center">
            <div class="col-12">
                @if (session('status'))
                    <div class="alert alert-success d-print-none" role="alert">
                        {{ session('status') }}
                    </div>
                @endif
                <div class="card" id="card-order-details">
                    @include('inc.order-details')
                </div>
            </div>
        </div>
        <div class="row justify-content-center item-container">
            <div class="col-12">
                @include('inc.item')
            </div>
        </div>
        <div class="row d-print-none">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <button type="button" class="btn btn-secondary mr-2 float-right d-print-none" v-on:click="addNewItem">+ Add Item</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        @include('inc.grand-total')
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@if (isset($order))
<div class="modal fade" id="deleteOrder" tabindex="-1" role="dialog" aria-labelledby="deleteOrderTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteOrderTitle">Delete Order</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this order?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{ route('orders.destroy', $order->id) }}" method="POST">
            @csrf {{-- Include CSRF protection --}}
            @method('DELETE')
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>
@endif
<div class="modal fade" id="deleteFile" tabindex="-1" role="dialog" aria-labelledby="deleteFileTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteOrderTitle">Delete Attached File</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete the attached file?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-danger" id="delete-file-confirm-button" data-dismiss="modal">Delete</button>
      </div>
    </div>
  </div>
</div>
<div id="fileUploadSection" class="d-none d-print-none">
  <form method="post" id="upload_form" enctype="multipart/form-data">
    @csrf {{-- Include CSRF protection --}}
    <input type="file" id="file-to-upload" name="file-to-upload" accept=".ai,.bmp,.eps,.gif,.jpg,.jpeg,.pdf,.png,.psd">
  </form>
</div>
<script type="text/javascript">
   $(function () {
       $('#due-date').datetimepicker({
           format: 'DD/MM/YYYY',
       });
       $('#order-date').datetimepicker({
           format: 'DD/MM/YYYY',
       });
       $('#dispatch-date').datetimepicker({
           format: 'DD/MM/YYYY',
       });
       $('#status').on('change', function(){
          if(this.value == 'Dispatched-Invoice' && !$('#dispatch-date > input').val()){
             $('#dispatch-date > input').val('{{ date('d/m/Y') }}');
          }
       });
   });
</script>
<script>
    var item = new Vue({
        el: '#orders',
        computed: {
          total: function(){

            function getSum(total, num) {
              return total + parseFloat(num.subtotal);
            }

            var total = this.items.reduce( getSum, 0 );

            return total.toFixed(2);
          }
        },
        data: {
            items:[
                @if (isset($order->items))
                    @foreach ($order->items as $item)
                        {
                            size: `{!! $item->size !!}`,
                            material: '{{$item->material}}',
                            thickness: '{{$item->thickness}}',
                            infill: '{{$item->infill}}',
                            holes: '{{$item->holes}}',
                            quantity: {!!$item->quantity ? $item->quantity : "''" !!},
                            price: {!!$item->price ? $item->price . '.toFixed(2)' : "''" !!},
                            subtotal: ({{$item->quantity ? $item->quantity : 0}} * {{$item->price ? $item->price : 0}}).toFixed(2),
                            engraving: `{!! $item->engraving !!}`,
                            completed: `{!! $item->completed ? $item->completed : '' !!}`
                        },
                    @endforeach
                @else
                {
                    size: '',
                    material: '',
                    thickness: '',
                    infill: '',
                    holes: '',
                    quantity: '',
                    price: 0,
                    subtotal: 0,
                    engraving: '',
                    completed: ''
                }
                @endif
            ],
        },
        methods: {
            addNewItem: function () {
                this.items.push({
                    size: '',
                    material: '',
                    thickness: '',
                    infill: '',
                    holes: '',
                    quantity: '',
                    price: 0,
                    subtotal: 0,
                    engraving: '',
                    completed: ''
                })
            },
            deleteItem: function (index){
                this.items.splice(index, 1);
            },
            updateSubtotal: function (index){
               this.items[index].subtotal = (this.items[index].quantity * this.items[index].price).toFixed(2);
           }
        }
    })
</script>
<script>
// Disable form submissions if there are invalid fields
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
<script>
$(document).ready(function() {
  $('.jquery-print').click(function() {
      window.print();
  });
  $("#file-to-upload").change(function() {
    $("#upload_form").submit();
  });
  $('#upload_form').on('submit', function(event){
    event.preventDefault();
    $.ajax({
      url:"{{ route('ajaxuploadfile.action') }}",
      method:"POST",
      data:new FormData(this),
      dataType:'JSON',
      contentType: false,
      cache: false,
      processData: false,
      success:function(data)
      {
        $('#attach-file-button').hide();
        $('#uploaded_file').html(data.uploaded_file);
        $('#attached_file').val(data.attached_file);
      }
    })
  });
  $('#delete-file-confirm-button').click(function() {
    $('#attached_file').val('');
    $('#uploaded_file').html('<label class="btn btn-secondary btn-file" for="file-to-upload" id="attach-file-button"><i class="fas fa-file-upload"></i> Attach File</label><p><small class="text-danger"><strong>Important:</strong> File will not be deleted until the order is updated</small><br><small><strong>Accepted file types:</strong> AI, BMP, EPS, GIF, JPG, JPEG, PDF, PNG, PSD - <strong>Max file size:</strong> 25MB</small></p>');
  });

  @if (Route::current()->getName() == 'orders.create') // We're only loading this on the Create Order page

  function getDueDate(orderDate){ // A function that we can recall when certain events change and pass in a date if required
      var orderDate = orderDate || moment(); // If a date is passed in, then we'll use that, if not then we'll use 'now'
      orderDate = moment(orderDate,'DD/MM/YYYY'); // Format the date using Moment.js

      var days = 7; // This refers to the number of days we wish to add to the original date

      while (days > 0) {
         date = orderDate.add(1, 'days'); // Add 1 day to the date
         if (orderDate.isoWeekday() !== 6 && orderDate.isoWeekday() !== 7) { // If it's not a weekend
            days -= 1; // Remove 1 from the count
         }
      }

      $('#due-date input').val(date.format('DD/MM/YYYY'));
  }

  getDueDate(); // Ran on page load

  $('#order-date input').on("change keyup paste", function(){
     getDueDate( $(this).val() );
  });

  $("#order-date").on("change.datetimepicker", function(){
     getDueDate( $('#order-date input').val() );
  });
  @endif
});
</script>
@endsection